// Package httpapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.1.0 DO NOT EDIT.
package httpapi

// Address defines model for Address.
type Address struct {
	AddressLine1 *string `json:"addressLine1,omitempty"`
	AddressLine2 *string `json:"addressLine2,omitempty"`
	City         *string `json:"city,omitempty"`
	Code         *string `json:"code,omitempty"`
	Country      *string `json:"country,omitempty"`
	Id           *int    `json:"id,omitempty"`
	State        *string `json:"state,omitempty"`
}

// PasswordResetRequest defines model for PasswordResetRequest.
type PasswordResetRequest struct {
	Email string `json:"email"`
}

// PasswordUpdateRequest defines model for PasswordUpdateRequest.
type PasswordUpdateRequest struct {
	NewPassword *string `json:"newPassword,omitempty"`
	Token       string  `json:"token"`
}

// UserLoginRequest defines model for UserLoginRequest.
type UserLoginRequest struct {
	Password string `json:"password"`
	Username string `json:"username"`
}

// UserLoginResponse defines model for UserLoginResponse.
type UserLoginResponse struct {
	AccessToken *string `json:"accessToken,omitempty"`
}

// UserProfile defines model for UserProfile.
type UserProfile struct {
	Email    *string `json:"email,omitempty"`
	Name     *string `json:"name,omitempty"`
	Username *string `json:"username,omitempty"`
}

// UserRegistrationRequest defines model for UserRegistrationRequest.
type UserRegistrationRequest struct {
	Email    string  `json:"email"`
	Name     *string `json:"name,omitempty"`
	Password string  `json:"password"`
	Username string  `json:"username"`
}

// UserRegistrationResponse defines model for UserRegistrationResponse.
type UserRegistrationResponse struct {
	Email    *string `json:"email,omitempty"`
	Id       *int    `json:"id,omitempty"`
	Username *string `json:"username,omitempty"`
}

// PostUsersJSONRequestBody defines body for PostUsers for application/json ContentType.
type PostUsersJSONRequestBody = UserRegistrationRequest

// PostUsersLoginJSONRequestBody defines body for PostUsersLogin for application/json ContentType.
type PostUsersLoginJSONRequestBody = UserLoginRequest

// PostUsersPasswordResetJSONRequestBody defines body for PostUsersPasswordReset for application/json ContentType.
type PostUsersPasswordResetJSONRequestBody = PasswordResetRequest

// PutUsersPasswordResetJSONRequestBody defines body for PutUsersPasswordReset for application/json ContentType.
type PutUsersPasswordResetJSONRequestBody = PasswordUpdateRequest

// PutUsersUserIdAddressesAddressIdJSONRequestBody defines body for PutUsersUserIdAddressesAddressId for application/json ContentType.
type PutUsersUserIdAddressesAddressIdJSONRequestBody = Address
