openapi: "3.1.0"
info:
  title: User domain APIs
  version: "1.0"
  description:
    User APIs lets user register, login, logout and view their profile

servers:
  - url: localhost:7074

paths:
  /users:
    post:
      summary: Create a new user
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRegistrationRequest'

      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserRegistrationResponse'
        '400':
          description: Bad Request
        '409':
          description: Conflict
        '5XX':
          description: Server Error

  /users/login:
    post:
      summary: User login
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserLoginRequest'

      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserLoginResponse'
        '401':
          description: Unauthorized
        '5XX':
          description: Server Error

  /users/{userId}:
    get:
      summary: Get user profile
      parameters:
        - in: path
          name: userId
          required: true
          schema: 
            type: integer

      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProfile'
        '404':
          description: Not Found
        '5XX':
          description: Server Error
    
    post: 
      summary: Add user address
      parameters:
        - in: path
          name: userId
          required: true
          schema: 
            type: integer

      responses:
        '201':
          description: Created
        '400':
          description: Bad Request
        '401':
          description: Conflict
        '5XX':
          description: Server Error
            
  /users/{userId}/addresses/{addressId}:
    put:
      summary: Update user address
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: integer
        - in: path
          name: addressId
          required: true
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Address'
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
        '404':
          description: Not Found
    delete:
      summary: Delete user address
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: integer
        - in: path
          name: addressId
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: No Content
        '404':
          description: Not Found

  /users/password-reset:
    post:
      summary: Initiate password reset
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PasswordResetRequest'
      responses:
        '204':
          description: No Content
        '400':
          description: Bad Request
    put:
      summary: Update password
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PasswordUpdateRequest'
      responses:
        '204':
          description: No Content
        '400':
          description: Bad Request
        '401':
          description: Unauthorized

components:
  schemas:
    UserRegistrationRequest:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
        username:
          type: string
        name:
          type: string
      required:
        - email
        - password
        - username

    UserRegistrationResponse:
      type: object
      properties:
        id:
          type: integer
        username:
          type: string
        email:
          type: string
    
    UserLoginRequest:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
      required:
        - username
        - password

    UserLoginResponse:
      type: object
      properties:
        accessToken:
          type: string

    UserProfile:
      type: object
      properties: 
        name:
          type: string
        username:
          type: string
        email:
          type: string

    Address:
      type: object
      properties:
        id:
          type: integer
        addressLine1:
          type: string
        addressLine2:
          type: string
        city:
          type: string
        state:
          type: string
        country:
          type: string
        code:
          type: string

    PasswordResetRequest:
      type: object
      properties:
        email:
          type: string
      required:
        - email

    PasswordUpdateRequest:
      type: object
      properties:
        token:
          type: string
        newPassword:
          type: string
      required:
        - token
        - password

